name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Verify Maven installation
        run: mvn -version

      # List files to verify the location of the Makefile
      - name: List project files
        run: ls -al .github/workflows

      # Run the actual Makefile if it exists in the root directory or any other directory
#      - name: Run Makefile
#        run: make -f path/to/your/Makefile
