# Variables
  MAVEN = mvn
  GIT = git

# Phony targets
.PHONY: all clean compile verify check distcheck package

# Default target
all: clean compile package

# Clean build artifacts
clean:
  $(MAVEN) clean

# Compile the code
compile:
  $(MAVEN) compile

# Verify the application
verify:
  $(MAVEN) verify

# Run tests
check:
  $(MAVEN) test

# Distcheck: package and verify everything is working for distribution
distcheck: clean compile check package
  @echo "All checks passed. Ready for distribution."

# Package the application
package:
  $(MAVEN) package
